---

# tags:
#   config:                docker-compose -> configure
#   up:                    docker-compose -> create and start containers
#   start:                 docker-compose -> start containers
#   stop:                  docker-compose -> stop containers
#   remove:                docker-compose -> remove containers
#   removeall:             docker-compose -> remove containers and volumes
#
#   config_service:        configure systemd to manage containers with docker-compose
#   start_service:         start service
#   stop_service:          stop service
#   restart_service:       restart service


- name: haproxy (compose + systemd)
  hosts: haproxy
  vars:
    project_name: haproxy
    #
    systemd_filename_source: model01.service
    systemd_filename_target: haproxy.service
    systemd_description: "HAProxy container"
    #
    docker_compose_conf_dir: /etc/docker-compose
    docker_compose_files_dir: haproxy
    docker_compose_filename_source: docker-compose.yml
    docker_compose_filename: docker-compose.yml
  roles:
    - containers
    - systemd
