---

# tags:
#   config:                docker-compose -> configure
#   up:                    docker-compose -> create and start containers
#   start:                 docker-compose -> start containers
#   stop:                  docker-compose -> stop containers
#   remove:                docker-compose -> remove containers
#   removeall:             docker-compose -> remove containers and volumes
#
#   systemd_config:        configure systemd to manage containers with docker-compose


- name: madsonic
  hosts: madsonic
  vars:
    project_name: madsonic
    #
    systemd_filename_source: model01.service
    systemd_filename_target: madsonic.service
    systemd_description: "Madsonic container"
    #
    docker_compose_conf_dir: /etc/docker-compose
    docker_compose_files_dir: madsonic
    docker_compose_filename_source: docker-compose.yml
    docker_compose_filename: docker-compose.yml
    #
    datas_vol: "{{ madsonic_data }}"
  roles:
    - containers
    - systemd
