version: '3'

volumes:
  certificates:

networks:
  legacy:
    external:
      name: openvpn_legacy

services:
  letsencrypt_server:
    container_name: letsencrypt
    image: flem/letsencrypt-nginx
    networks:
      legacy:
        aliases:
          - letsencryptserver
#    restart: always
    volumes:
      - certificates:/etc/letsencrypt
    environment:
      - DOMAIN1={{ servername1 }}
      - EMAIL1={{ serveradmin1 }}
      - DOMAIN2={{ servername2 }}
      - EMAIL2={{ serveradmin2 }}
      - DOMAIN3={{ servername3 }}
      - EMAIL3={{ serveradmin3 }}
