---
# default

# specific HubiC 01
hubic01_datas_dir: "/home/user/hubic_datas"
hubic01_config_dir: "/home/user/hubiC"
hubic01_email: "user@domain.tld"
hubic01_password: "xxxxxxxx"


servername1: "www.site.tld"
serveradmin1: "admin@site.tld"
servername2: "www.site2.tld"
serveradmin2: "admin@site2.tld"
servername3: "www.site3.tld"
serveradmin3: "admin@site3.tld"


ovpn_data: "ovpn-data"


letsencrypt_data: "letsencrypt_certificates"


madsonic_config_path: "/tmp/config"
madsonic_media_path: "/tmp/media"


airsonic_data_path: "/tmp/data"
airsonic_music_path: "/tmp/music"
airsonic_playlists_path: "/tmp/playlists"
airsonic_podcasts_path: "/tmp/podcasts"


domoticz_db_path: "/tmp/db"
domoticz_backups_path: "/tmp/backups"


haproxy_conf_files:
  - { src: 'haproxy.j2', dest: 'haproxy.cfg' }


optional_files:
  prometheus:
    project: monitoring
    directory: /etc/docker-compose/monitoring/docker/prometheus
    duid: 0
    dgid: 0
    dmod: 755
    file: prometheus.yml
    fuid: 0
    fgid: 0
    fmod: 644
